# Generated by Django 2.2.6 on 2020-04-03 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.CharField(default='', max_length=150, verbose_name='URL ID')),
                ('product_name', models.CharField(max_length=386, verbose_name='Product Name')),
                ('product_id', models.IntegerField(verbose_name='Product ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Reserved', max_length=32)),
                ('note', models.TextField(blank=True, max_length='500', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
